version: "3.3"
services:
  devenv:
    image: pelger/aiasaservice
    ports:
      - "127.0.0.1:8888:8888"
    volumes:
      - "..:/home/dev/work"
    environment:
      AWS_ACCESS_KEY_ID: <your access key id>
      AWS_SECRET_ACCESS_KEY: <your secret access key>
      AWS_DEFAULT_REGION: eu-west-1
      AWS_REGION: eu-west-1
      AWS_ACCOUNT_ID: <your account id>
      MY_CRAWLER_QUEUE: MyCrawlerQueue
      MY_ANALYSIS_QUEUE: MyAnalysisQueue
      MY_BUCKET_NAME: <your bucket name>
